load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(name = "androidsdk")

local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.appcompat:appcompat:1.0.2",
        "androidx.annotation:annotation:1.0.2",
        "androidx.test.ext:junit:1.1.0",
        "org.robolectric:robolectric:3.8",
        "org.robolectric:android-all:5.0.2_r3-robolectric-r0",
        "org.assertj:assertj-core:3.12.1"
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
