/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.bazelbuild.rules_jvm_external.resolver.gradle2.plugin;

import javax.inject.Inject;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.internal.logging.progress.ProgressLogger;
import org.gradle.internal.logging.progress.ProgressLoggerFactory;
import org.gradle.tooling.provider.model.ToolingModelBuilderRegistry;

public class CustomModelInjectionPlugin implements Plugin<Project> {
  private final ToolingModelBuilderRegistry registry;
  private final ProgressLoggerFactory progressLoggerFactory;

  @Inject
  public CustomModelInjectionPlugin(
      ToolingModelBuilderRegistry registry, ProgressLoggerFactory progressLoggerFactory) {
    this.registry = registry;
    this.progressLoggerFactory = progressLoggerFactory;
  }

  public void apply(Project project) {
    System.out.println("Progress logger factory: " + progressLoggerFactory);

    ProgressLogger pl = progressLoggerFactory.newOperation("magic");
    pl.setDescription("I like eating cheese");
    pl.start("Greeting", null);

    if (project == project.getRootProject()) {
      registry.register(new OutgoingArtifactsModelBuilder());
    }
  }
}
