# Auto-generated by https://github.com/menny/bazel-mvn-deps

# Loading a drop-in replacement for native.http_file
load('@bazel_tools//tools/build_defs/repo:http.bzl', 'http_file')

# Repository rules macro to be run in the WORKSPACE file.
def generate_workspace_rules():
    # from backport-util-concurrent:backport-util-concurrent:3.1
    http_file(name = 'main_deps___backport_util_concurrent__backport_util_concurrent__3_1',
        urls = ['https://repo1.maven.org/maven2/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar'],
        downloaded_file_path = 'backport-util-concurrent-3.1.jar',
        sha256 = 'f5759b7fcdfc83a525a036deedcbd32e5b536b625ebc282426f16ca137eb5902',
    )

    # from classworlds:classworlds:1.1-alpha-2
    http_file(name = 'main_deps___classworlds__classworlds__1_1_alpha_2',
        urls = ['https://repo1.maven.org/maven2/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar'],
        downloaded_file_path = 'classworlds-1.1-alpha-2.jar',
        sha256 = '2bf4e59f3acd106fea6145a9a88fe8956509f8b9c0fdd11eb96fee757269e3f3',
    )

    # from com.almworks.sqlite4java:sqlite4java:0.282
    http_file(name = 'main_deps___com_almworks_sqlite4java__sqlite4java__0_282',
        urls = ['https://repo1.maven.org/maven2/com/almworks/sqlite4java/sqlite4java/0.282/sqlite4java-0.282.jar'],
        downloaded_file_path = 'sqlite4java-0.282.jar',
        sha256 = '9e1d8dd83ca6003f841e3af878ce2dc7c22497493a7bb6d1b62ec1b0d0a83c05',
    )

    # from com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1
    http_file(name = 'main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework__2_1',
        urls = ['https://repo1.maven.org/maven2/com/google/android/apps/common/testing/accessibility/framework/accessibility-test-framework/2.1/accessibility-test-framework-2.1.jar'],
        downloaded_file_path = 'accessibility-test-framework-2.1.jar',
        sha256 = '7b0aa6ed7553597ce0610684a9f7eca8021eee218f2e2f427c04a7fbf5f920bd',
    )

    # from com.google.guava:guava:20.0
    http_file(name = 'main_deps___com_google_guava__guava__20_0',
        urls = ['https://repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar'],
        downloaded_file_path = 'guava-20.0.jar',
        sha256 = '36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8',
    )

    # from com.google.protobuf:protobuf-java:2.6.1
    http_file(name = 'main_deps___com_google_protobuf__protobuf_java__2_6_1',
        urls = ['https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.jar'],
        downloaded_file_path = 'protobuf-java-2.6.1.jar',
        sha256 = '55aa554843983f431df5616112cf688d38aa17c132357afd1c109435bfdac4e6',
    )

    # from com.ibm.icu:icu4j:53.1
    http_file(name = 'main_deps___com_ibm_icu__icu4j__53_1',
        urls = ['https://repo1.maven.org/maven2/com/ibm/icu/icu4j/53.1/icu4j-53.1.jar'],
        downloaded_file_path = 'icu4j-53.1.jar',
        sha256 = 'e37a4467bac5cdeb02c5c4b8e5063d2f4e67b69e3c7df6d6b610f13185572bab',
    )

    # from com.thoughtworks.xstream:xstream:1.4.8
    http_file(name = 'main_deps___com_thoughtworks_xstream__xstream__1_4_8',
        urls = ['https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar'],
        downloaded_file_path = 'xstream-1.4.8.jar',
        sha256 = 'a219a1abf948400b669d08be73a6f9209fb720d237e5ff74c223bffe5f9df93d',
    )

    # from nekohtml:nekohtml:1.9.6.2
    http_file(name = 'main_deps___nekohtml__nekohtml__1_9_6_2',
        urls = ['https://repo1.maven.org/maven2/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar'],
        downloaded_file_path = 'nekohtml-1.9.6.2.jar',
        sha256 = 'fdff6cfa9ed9cc911c842a5d2395f209ec621ef1239d46810e9e495809d3ae09',
    )

    # from nekohtml:xercesMinimal:1.9.6.2
    http_file(name = 'main_deps___nekohtml__xercesMinimal__1_9_6_2',
        urls = ['https://repo1.maven.org/maven2/nekohtml/xercesMinimal/1.9.6.2/xercesMinimal-1.9.6.2.jar'],
        downloaded_file_path = 'xercesMinimal-1.9.6.2.jar',
        sha256 = '95b8b357d19f63797dd7d67622fd3f18374d64acbc6584faba1c7759a31e8438',
    )

    # from org.apache.ant:ant-launcher:1.8.0
    http_file(name = 'main_deps___org_apache_ant__ant_launcher__1_8_0',
        urls = ['https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.0/ant-launcher-1.8.0.jar'],
        downloaded_file_path = 'ant-launcher-1.8.0.jar',
        sha256 = 'da9fd92eacdf63daf0be52eb71accc10ff7943a85d7aac9ea96cf7e03ee3d3cc',
    )

    # from org.apache.ant:ant:1.8.0
    http_file(name = 'main_deps___org_apache_ant__ant__1_8_0',
        urls = ['https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.0/ant-1.8.0.jar'],
        downloaded_file_path = 'ant-1.8.0.jar',
        sha256 = '0251dbb938740ace07a53675113eee753ba389db65aebc814b175af50321620e',
    )

    # from org.apache.maven.wagon:wagon-file:1.0-beta-6
    http_file(name = 'main_deps___org_apache_maven_wagon__wagon_file__1_0_beta_6',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-file/1.0-beta-6/wagon-file-1.0-beta-6.jar'],
        downloaded_file_path = 'wagon-file-1.0-beta-6.jar',
        sha256 = '7298feeb36ff14dd933c38e62585fb9973fea32fb3c4bc5379428cb1aac5dd3c',
    )

    # from org.apache.maven.wagon:wagon-http-lightweight:1.0-beta-6
    http_file(name = 'main_deps___org_apache_maven_wagon__wagon_http_lightweight__1_0_beta_6',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http-lightweight/1.0-beta-6/wagon-http-lightweight-1.0-beta-6.jar'],
        downloaded_file_path = 'wagon-http-lightweight-1.0-beta-6.jar',
        sha256 = 'be214032de23c6b520b79c1ccdb160948e0c67ed7c11984b7ec4ca5537867b4e',
    )

    # from org.apache.maven.wagon:wagon-http-shared:1.0-beta-6
    http_file(name = 'main_deps___org_apache_maven_wagon__wagon_http_shared__1_0_beta_6',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http-shared/1.0-beta-6/wagon-http-shared-1.0-beta-6.jar'],
        downloaded_file_path = 'wagon-http-shared-1.0-beta-6.jar',
        sha256 = 'f095c882716d49269a806685dcb256fa6a36389b2713ac56bb758bf8693565a2',
    )

    # from org.apache.maven.wagon:wagon-provider-api:1.0-beta-6
    http_file(name = 'main_deps___org_apache_maven_wagon__wagon_provider_api__1_0_beta_6',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.jar'],
        downloaded_file_path = 'wagon-provider-api-1.0-beta-6.jar',
        sha256 = 'e116f32edcb77067289a3148143f2c0c97b27cf9a1342f8108ee37dec4868861',
    )

    # from org.apache.maven:maven-ant-tasks:2.1.3
    http_file(name = 'main_deps___org_apache_maven__maven_ant_tasks__2_1_3',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar'],
        downloaded_file_path = 'maven-ant-tasks-2.1.3.jar',
        sha256 = 'f16b5ea711dfe0323454b880180aa832420ec039936e4aa75fb978748634808a',
    )

    # from org.apache.maven:maven-artifact-manager:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_artifact_manager__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.jar'],
        downloaded_file_path = 'maven-artifact-manager-2.2.1.jar',
        sha256 = 'd1e247c4ed3952385fd704ac9db2a222247cfe7d20508b4f3c76b90f857952ed',
    )

    # from org.apache.maven:maven-artifact:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_artifact__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.jar'],
        downloaded_file_path = 'maven-artifact-2.2.1.jar',
        sha256 = 'd53062ffe8677a4f5e1ad3a1d1fa37ed600fab39166d39be7ed204635c5f839b',
    )

    # from org.apache.maven:maven-error-diagnostics:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_error_diagnostics__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.jar'],
        downloaded_file_path = 'maven-error-diagnostics-2.2.1.jar',
        sha256 = 'b3005544708f8583e455c22b09a4940596a057108bccdadb9db4d8e048091fed',
    )

    # from org.apache.maven:maven-model:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_model__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar'],
        downloaded_file_path = 'maven-model-2.2.1.jar',
        sha256 = '153b32f474fd676ec36ad807c508885005139140fc92168bb76bf6be31f8efb8',
    )

    # from org.apache.maven:maven-plugin-registry:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_plugin_registry__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.jar'],
        downloaded_file_path = 'maven-plugin-registry-2.2.1.jar',
        sha256 = '4ad0673155d7e0e5cf6d13689802d8d507f38e5ea00a6d2fb92aef206108213d',
    )

    # from org.apache.maven:maven-profile:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_profile__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.jar'],
        downloaded_file_path = 'maven-profile-2.2.1.jar',
        sha256 = 'ecaffef655fea6b138f0855a12f7dbb59fc0d6bffb5c1bfd31803cccb49ea08c',
    )

    # from org.apache.maven:maven-project:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_project__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.jar'],
        downloaded_file_path = 'maven-project-2.2.1.jar',
        sha256 = '24ddb65b7a6c3befb6267ce5f739f237c84eba99389265c30df67c3dd8396a40',
    )

    # from org.apache.maven:maven-repository-metadata:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_repository_metadata__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar'],
        downloaded_file_path = 'maven-repository-metadata-2.2.1.jar',
        sha256 = '5fe283f47b0e7f7d95a4252af3fa7a0db4d8f080cd9df308608c0472b8f168a1',
    )

    # from org.apache.maven:maven-settings:2.2.1
    http_file(name = 'main_deps___org_apache_maven__maven_settings__2_2_1',
        urls = ['https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar'],
        downloaded_file_path = 'maven-settings-2.2.1.jar',
        sha256 = '9a9f556713a404e770c9dbdaed7eb086078014c989291960c76fdde6db4192f7',
    )

    # from org.bouncycastle:bcprov-jdk15on:1.52
    http_file(name = 'main_deps___org_bouncycastle__bcprov_jdk15on__1_52',
        urls = ['https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.jar'],
        downloaded_file_path = 'bcprov-jdk15on-1.52.jar',
        sha256 = '0dc4d181e4d347893c2ddbd2e6cd5d7287fc651c03648fa64b2341c7366b1773',
    )

    # from org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1
    http_file(name = 'main_deps___org_codehaus_plexus__plexus_container_default__1_0_alpha_9_stable_1',
        urls = ['https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar'],
        downloaded_file_path = 'plexus-container-default-1.0-alpha-9-stable-1.jar',
        sha256 = '7c758612888782ccfe376823aee7cdcc7e0cdafb097f7ef50295a0b0c3a16edf',
    )

    # from org.codehaus.plexus:plexus-utils:1.5.15
    http_file(name = 'main_deps___org_codehaus_plexus__plexus_utils__1_5_15',
        urls = ['https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar'],
        downloaded_file_path = 'plexus-utils-1.5.15.jar',
        sha256 = '2ca121831e597b4d8f2cb22d17c5c041fc23a7777ceb6bfbdd4dfb34bbe7d997',
    )

    # from org.hamcrest:hamcrest-core:1.3
    http_file(name = 'main_deps___org_hamcrest__hamcrest_core__1_3',
        urls = ['https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar'],
        downloaded_file_path = 'hamcrest-core-1.3.jar',
        sha256 = '66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9',
    )

    # from org.hamcrest:hamcrest-library:1.3
    http_file(name = 'main_deps___org_hamcrest__hamcrest_library__1_3',
        urls = ['https://repo1.maven.org/maven2/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar'],
        downloaded_file_path = 'hamcrest-library-1.3.jar',
        sha256 = '711d64522f9ec410983bd310934296da134be4254a125080a0416ec178dfad1c',
    )

    # from org.ow2.asm:asm-commons:5.0.1
    http_file(name = 'main_deps___org_ow2_asm__asm_commons__5_0_1',
        urls = ['https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar'],
        downloaded_file_path = 'asm-commons-5.0.1.jar',
        sha256 = 'fb1cb7fa27d892712ced8fbf8d027eb5052ecd3999dba1ba47824357accb40e7',
    )

    # from org.ow2.asm:asm-tree:5.0.1
    http_file(name = 'main_deps___org_ow2_asm__asm_tree__5_0_1',
        urls = ['https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar'],
        downloaded_file_path = 'asm-tree-5.0.1.jar',
        sha256 = 'ff2aceed10da9930a44f6c8f81c6372d5e55eb59c4e0ea9d37f77dfd765fa9fa',
    )

    # from org.ow2.asm:asm:5.0.1
    http_file(name = 'main_deps___org_ow2_asm__asm__5_0_1',
        urls = ['https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar'],
        downloaded_file_path = 'asm-5.0.1.jar',
        sha256 = '56057490cbc1eeae6227e6eb5c6d5b324b77429b8a78d15027c77d491ef9c675',
    )

    # from org.robolectric:android-all:5.0.2_r3-robolectric-r0
    http_file(name = 'main_deps___org_robolectric__android_all__5_0_2_r3_robolectric_r0',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.jar'],
        downloaded_file_path = 'android-all-5.0.2_r3-robolectric-r0.jar',
        sha256 = '5e63d4c7f2c691afed648bf0675e0b0a76d19f0e23d93705f4faf9ed3b2734de',
    )

    # from org.robolectric:annotations:3.8
    http_file(name = 'main_deps___org_robolectric__annotations__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/annotations/3.8/annotations-3.8.jar'],
        downloaded_file_path = 'annotations-3.8.jar',
        sha256 = '8eab08facfe2a8cd22f6a09f4378f012a5985c0d4f4ad4e203e00f75b5568458',
    )

    # from org.robolectric:junit:3.8
    http_file(name = 'main_deps___org_robolectric__junit__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/junit/3.8/junit-3.8.jar'],
        downloaded_file_path = 'junit-3.8.jar',
        sha256 = '042575dbc95dc82ec046d13438ccda578917ce786d2f464cba0eb18da1f412cb',
    )

    # from org.robolectric:resources:3.8
    http_file(name = 'main_deps___org_robolectric__resources__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/resources/3.8/resources-3.8.jar'],
        downloaded_file_path = 'resources-3.8.jar',
        sha256 = '6d11e6d39df8eda837c52319cf8d6bef424df45be6f29b3a731707832eb6ffc1',
    )

    # from org.robolectric:robolectric:3.8
    http_file(name = 'main_deps___org_robolectric__robolectric__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/robolectric/3.8/robolectric-3.8.jar'],
        downloaded_file_path = 'robolectric-3.8.jar',
        sha256 = '34908fc858e6e4113be2cf97fe55d3ffa4462bf7183d466542582ca1898ce60a',
    )

    # from org.robolectric:sandbox:3.8
    http_file(name = 'main_deps___org_robolectric__sandbox__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/sandbox/3.8/sandbox-3.8.jar'],
        downloaded_file_path = 'sandbox-3.8.jar',
        sha256 = 'cc257dc75c5af9e62a43572ac89dff4d8520427307cf973e6b663c88fb000720',
    )

    # from org.robolectric:shadowapi:3.8
    http_file(name = 'main_deps___org_robolectric__shadowapi__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/shadowapi/3.8/shadowapi-3.8.jar'],
        downloaded_file_path = 'shadowapi-3.8.jar',
        sha256 = '28bc24cb5c4b4030852cebebfd5f12536d03088892cb3c8b1d1379297087aca8',
    )

    # from org.robolectric:shadows-framework:3.8
    http_file(name = 'main_deps___org_robolectric__shadows_framework__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/shadows-framework/3.8/shadows-framework-3.8.jar'],
        downloaded_file_path = 'shadows-framework-3.8.jar',
        sha256 = '83548db7249edf1af87e1a1f4d8f4eec3e85d6220161da601e6f6398476911b2',
    )

    # from org.robolectric:utils:3.8
    http_file(name = 'main_deps___org_robolectric__utils__3_8',
        urls = ['https://repo1.maven.org/maven2/org/robolectric/utils/3.8/utils-3.8.jar'],
        downloaded_file_path = 'utils-3.8.jar',
        sha256 = 'e945d04d40e37554e02d4be1bc3abf9bede45375c843aa36d10ccb6b63edbf34',
    )

    # from xmlpull:xmlpull:1.1.3.1
    http_file(name = 'main_deps___xmlpull__xmlpull__1_1_3_1',
        urls = ['https://repo1.maven.org/maven2/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar'],
        downloaded_file_path = 'xmlpull-1.1.3.1.jar',
        sha256 = '34e08ee62116071cbb69c0ed70d15a7a5b208d62798c59f2120bb8929324cb63',
    )

    # from xpp3:xpp3_min:1.1.4c
    http_file(name = 'main_deps___xpp3__xpp3_min__1_1_4c',
        urls = ['https://repo1.maven.org/maven2/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar'],
        downloaded_file_path = 'xpp3_min-1.1.4c.jar',
        sha256 = 'bfc90e9e32d0eab1f397fb974b5f150a815188382ac41f372a7149d5bc178008',
    )


# Transitive rules macro to be run in the BUILD.bazel file.
# If you use kt_* rules, you MUST provide the correct rule implementation when call this macro, if you decide
# not to provide those implementations we'll try to use java_* rules.

# This is a help macro to handle Kotlin rules.
def kotlin_jar_support(name, deps, exports, runtime_deps, jar, kt_jvm_import=None, kt_jvm_library=None):
    #In case the developer did not provide a kt_* impl, we'll try to use java_*, should work
    if kt_jvm_import == None:
        native.java_import(name = name,
            jars = [jar],
            deps = deps,
            exports = exports,
            runtime_deps = runtime_deps,
        )
    else:
        kt_jvm_import(name = '{}_kotlin_jar'.format(name),
            jars = [jar],
        )
        kt_jvm_library(name = name,
            deps = deps + [':{}_kotlin_jar'.format(name)],
            exports = exports + [':{}_kotlin_jar'.format(name)],
            runtime_deps = runtime_deps,
        )

def generate_transitive_dependency_targets(kt_jvm_import=None, kt_jvm_library=None):
    # from backport-util-concurrent:backport-util-concurrent:3.1
    native.alias(name = 'main_deps___backport_util_concurrent__backport_util_concurrent',
        actual = ':main_deps___backport_util_concurrent__backport_util_concurrent__3_1',
        visibility = ['//visibility:public'],
    )

    # from backport-util-concurrent:backport-util-concurrent:3.1
    native.java_import(name = 'main_deps___backport_util_concurrent__backport_util_concurrent__3_1',
        jars = ['@main_deps___backport_util_concurrent__backport_util_concurrent__3_1//file'],
        tags = ['maven_coordinates=backport-util-concurrent:backport-util-concurrent:3.1'],
        licenses = ['unencumbered'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from classworlds:classworlds:1.1-alpha-2
    native.alias(name = 'main_deps___classworlds__classworlds',
        actual = ':main_deps___classworlds__classworlds__1_1_alpha_2',
        visibility = ['//visibility:public'],
    )

    # from classworlds:classworlds:1.1-alpha-2
    native.java_import(name = 'main_deps___classworlds__classworlds__1_1_alpha_2',
        jars = ['@main_deps___classworlds__classworlds__1_1_alpha_2//file'],
        tags = ['maven_coordinates=classworlds:classworlds:1.1-alpha-2'],
        licenses = [],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.almworks.sqlite4java:sqlite4java:0.282
    native.alias(name = 'main_deps___com_almworks_sqlite4java__sqlite4java',
        actual = ':main_deps___com_almworks_sqlite4java__sqlite4java__0_282',
        visibility = ['//visibility:public'],
    )

    # from com.almworks.sqlite4java:sqlite4java:0.282
    native.java_import(name = 'main_deps___com_almworks_sqlite4java__sqlite4java__0_282',
        jars = ['@main_deps___com_almworks_sqlite4java__sqlite4java__0_282//file'],
        tags = ['maven_coordinates=com.almworks.sqlite4java:sqlite4java:0.282'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1
    native.alias(name = 'main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework',
        actual = ':main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework__2_1',
        visibility = ['//visibility:public'],
    )

    # from com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1
    native.java_import(name = 'main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework__2_1',
        jars = ['@main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework__2_1//file'],
        tags = ['maven_coordinates=com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1'],
        licenses = ['notice'],
        deps = [
            ':main_deps___com_google_protobuf__protobuf_java',
            ':main_deps___org_hamcrest__hamcrest_core',
            ':main_deps___org_hamcrest__hamcrest_library',
        ],
        exports = [
            ':main_deps___com_google_protobuf__protobuf_java',
            ':main_deps___org_hamcrest__hamcrest_core',
            ':main_deps___org_hamcrest__hamcrest_library',
        ],
        runtime_deps = [],
    )

    # from com.google.guava:guava:20.0
    native.alias(name = 'main_deps___com_google_guava__guava',
        actual = ':main_deps___com_google_guava__guava__20_0',
        visibility = ['//visibility:public'],
    )

    # from com.google.guava:guava:20.0
    native.java_import(name = 'main_deps___com_google_guava__guava__20_0',
        jars = ['@main_deps___com_google_guava__guava__20_0//file'],
        tags = ['maven_coordinates=com.google.guava:guava:20.0'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.protobuf:protobuf-java:2.6.1
    native.alias(name = 'main_deps___com_google_protobuf__protobuf_java',
        actual = ':main_deps___com_google_protobuf__protobuf_java__2_6_1',
        visibility = ['//visibility:public'],
    )

    # from com.google.protobuf:protobuf-java:2.6.1
    native.java_import(name = 'main_deps___com_google_protobuf__protobuf_java__2_6_1',
        jars = ['@main_deps___com_google_protobuf__protobuf_java__2_6_1//file'],
        tags = ['maven_coordinates=com.google.protobuf:protobuf-java:2.6.1'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.ibm.icu:icu4j:53.1
    native.alias(name = 'main_deps___com_ibm_icu__icu4j',
        actual = ':main_deps___com_ibm_icu__icu4j__53_1',
        visibility = ['//visibility:public'],
    )

    # from com.ibm.icu:icu4j:53.1
    native.java_import(name = 'main_deps___com_ibm_icu__icu4j__53_1',
        jars = ['@main_deps___com_ibm_icu__icu4j__53_1//file'],
        tags = ['maven_coordinates=com.ibm.icu:icu4j:53.1'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.thoughtworks.xstream:xstream:1.4.8
    native.alias(name = 'main_deps___com_thoughtworks_xstream__xstream',
        actual = ':main_deps___com_thoughtworks_xstream__xstream__1_4_8',
        visibility = ['//visibility:public'],
    )

    # from com.thoughtworks.xstream:xstream:1.4.8
    native.java_import(name = 'main_deps___com_thoughtworks_xstream__xstream__1_4_8',
        jars = ['@main_deps___com_thoughtworks_xstream__xstream__1_4_8//file'],
        tags = ['maven_coordinates=com.thoughtworks.xstream:xstream:1.4.8'],
        licenses = ['notice'],
        deps = [
            ':main_deps___xmlpull__xmlpull',
            ':main_deps___xpp3__xpp3_min',
        ],
        exports = [
            ':main_deps___xmlpull__xmlpull',
            ':main_deps___xpp3__xpp3_min',
        ],
        runtime_deps = [],
    )

    # from nekohtml:nekohtml:1.9.6.2
    native.alias(name = 'main_deps___nekohtml__nekohtml',
        actual = ':main_deps___nekohtml__nekohtml__1_9_6_2',
        visibility = ['//visibility:public'],
    )

    # from nekohtml:nekohtml:1.9.6.2
    native.java_import(name = 'main_deps___nekohtml__nekohtml__1_9_6_2',
        jars = ['@main_deps___nekohtml__nekohtml__1_9_6_2//file'],
        tags = ['maven_coordinates=nekohtml:nekohtml:1.9.6.2'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from nekohtml:xercesMinimal:1.9.6.2
    native.alias(name = 'main_deps___nekohtml__xercesMinimal',
        actual = ':main_deps___nekohtml__xercesMinimal__1_9_6_2',
        visibility = ['//visibility:public'],
    )

    # from nekohtml:xercesMinimal:1.9.6.2
    native.java_import(name = 'main_deps___nekohtml__xercesMinimal__1_9_6_2',
        jars = ['@main_deps___nekohtml__xercesMinimal__1_9_6_2//file'],
        tags = ['maven_coordinates=nekohtml:xercesMinimal:1.9.6.2'],
        licenses = [],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.apache.ant:ant-launcher:1.8.0
    native.alias(name = 'main_deps___org_apache_ant__ant_launcher',
        actual = ':main_deps___org_apache_ant__ant_launcher__1_8_0',
        visibility = ['//visibility:public'],
    )

    # from org.apache.ant:ant-launcher:1.8.0
    native.java_import(name = 'main_deps___org_apache_ant__ant_launcher__1_8_0',
        jars = ['@main_deps___org_apache_ant__ant_launcher__1_8_0//file'],
        tags = ['maven_coordinates=org.apache.ant:ant-launcher:1.8.0'],
        licenses = [],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.apache.ant:ant:1.8.0
    native.alias(name = 'main_deps___org_apache_ant__ant',
        actual = ':main_deps___org_apache_ant__ant__1_8_0',
        visibility = ['//visibility:public'],
    )

    # from org.apache.ant:ant:1.8.0
    native.java_import(name = 'main_deps___org_apache_ant__ant__1_8_0',
        jars = ['@main_deps___org_apache_ant__ant__1_8_0//file'],
        tags = ['maven_coordinates=org.apache.ant:ant:1.8.0'],
        licenses = [],
        deps = [':main_deps___org_apache_ant__ant_launcher'],
        exports = [':main_deps___org_apache_ant__ant_launcher'],
        runtime_deps = [],
    )

    # from org.apache.maven.wagon:wagon-file:1.0-beta-6
    native.alias(name = 'main_deps___org_apache_maven_wagon__wagon_file',
        actual = ':main_deps___org_apache_maven_wagon__wagon_file__1_0_beta_6',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven.wagon:wagon-file:1.0-beta-6
    native.java_import(name = 'main_deps___org_apache_maven_wagon__wagon_file__1_0_beta_6',
        jars = ['@main_deps___org_apache_maven_wagon__wagon_file__1_0_beta_6//file'],
        tags = ['maven_coordinates=org.apache.maven.wagon:wagon-file:1.0-beta-6'],
        licenses = ['notice'],
        deps = [':main_deps___org_apache_maven_wagon__wagon_provider_api'],
        exports = [':main_deps___org_apache_maven_wagon__wagon_provider_api'],
        runtime_deps = [],
    )

    # from org.apache.maven.wagon:wagon-http-lightweight:1.0-beta-6
    native.alias(name = 'main_deps___org_apache_maven_wagon__wagon_http_lightweight',
        actual = ':main_deps___org_apache_maven_wagon__wagon_http_lightweight__1_0_beta_6',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven.wagon:wagon-http-lightweight:1.0-beta-6
    native.java_import(name = 'main_deps___org_apache_maven_wagon__wagon_http_lightweight__1_0_beta_6',
        jars = ['@main_deps___org_apache_maven_wagon__wagon_http_lightweight__1_0_beta_6//file'],
        tags = ['maven_coordinates=org.apache.maven.wagon:wagon-http-lightweight:1.0-beta-6'],
        licenses = ['notice'],
        deps = [
            ':main_deps___org_apache_maven_wagon__wagon_http_shared',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
        ],
        exports = [
            ':main_deps___org_apache_maven_wagon__wagon_http_shared',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven.wagon:wagon-http-shared:1.0-beta-6
    native.alias(name = 'main_deps___org_apache_maven_wagon__wagon_http_shared',
        actual = ':main_deps___org_apache_maven_wagon__wagon_http_shared__1_0_beta_6',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven.wagon:wagon-http-shared:1.0-beta-6
    native.java_import(name = 'main_deps___org_apache_maven_wagon__wagon_http_shared__1_0_beta_6',
        jars = ['@main_deps___org_apache_maven_wagon__wagon_http_shared__1_0_beta_6//file'],
        tags = ['maven_coordinates=org.apache.maven.wagon:wagon-http-shared:1.0-beta-6'],
        licenses = ['notice'],
        deps = [
            ':main_deps___nekohtml__nekohtml',
            ':main_deps___nekohtml__xercesMinimal',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
        ],
        exports = [
            ':main_deps___nekohtml__nekohtml',
            ':main_deps___nekohtml__xercesMinimal',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven.wagon:wagon-provider-api:1.0-beta-6
    native.alias(name = 'main_deps___org_apache_maven_wagon__wagon_provider_api',
        actual = ':main_deps___org_apache_maven_wagon__wagon_provider_api__1_0_beta_6',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven.wagon:wagon-provider-api:1.0-beta-6
    native.java_import(name = 'main_deps___org_apache_maven_wagon__wagon_provider_api__1_0_beta_6',
        jars = ['@main_deps___org_apache_maven_wagon__wagon_provider_api__1_0_beta_6//file'],
        tags = ['maven_coordinates=org.apache.maven.wagon:wagon-provider-api:1.0-beta-6'],
        licenses = ['notice'],
        deps = [':main_deps___org_codehaus_plexus__plexus_utils'],
        exports = [':main_deps___org_codehaus_plexus__plexus_utils'],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-ant-tasks:2.1.3
    native.alias(name = 'main_deps___org_apache_maven__maven_ant_tasks',
        actual = ':main_deps___org_apache_maven__maven_ant_tasks__2_1_3',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-ant-tasks:2.1.3
    native.java_import(name = 'main_deps___org_apache_maven__maven_ant_tasks__2_1_3',
        jars = ['@main_deps___org_apache_maven__maven_ant_tasks__2_1_3//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-ant-tasks:2.1.3'],
        licenses = ['notice'],
        deps = [
            ':main_deps___classworlds__classworlds',
            ':main_deps___org_apache_ant__ant',
            ':main_deps___org_apache_maven__maven_artifact',
            ':main_deps___org_apache_maven__maven_artifact_manager',
            ':main_deps___org_apache_maven__maven_error_diagnostics',
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_apache_maven__maven_project',
            ':main_deps___org_apache_maven__maven_settings',
            ':main_deps___org_apache_maven_wagon__wagon_file',
            ':main_deps___org_apache_maven_wagon__wagon_http_lightweight',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___classworlds__classworlds',
            ':main_deps___org_apache_ant__ant',
            ':main_deps___org_apache_maven__maven_artifact',
            ':main_deps___org_apache_maven__maven_artifact_manager',
            ':main_deps___org_apache_maven__maven_error_diagnostics',
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_apache_maven__maven_project',
            ':main_deps___org_apache_maven__maven_settings',
            ':main_deps___org_apache_maven_wagon__wagon_file',
            ':main_deps___org_apache_maven_wagon__wagon_http_lightweight',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-artifact-manager:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_artifact_manager',
        actual = ':main_deps___org_apache_maven__maven_artifact_manager__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-artifact-manager:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_artifact_manager__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_artifact_manager__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-artifact-manager:2.2.1'],
        licenses = ['notice'],
        deps = [
            ':main_deps___backport_util_concurrent__backport_util_concurrent',
            ':main_deps___org_apache_maven__maven_artifact',
            ':main_deps___org_apache_maven__maven_repository_metadata',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___backport_util_concurrent__backport_util_concurrent',
            ':main_deps___org_apache_maven__maven_artifact',
            ':main_deps___org_apache_maven__maven_repository_metadata',
            ':main_deps___org_apache_maven_wagon__wagon_provider_api',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-artifact:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_artifact',
        actual = ':main_deps___org_apache_maven__maven_artifact__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-artifact:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_artifact__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_artifact__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-artifact:2.2.1'],
        licenses = ['notice'],
        deps = [':main_deps___org_codehaus_plexus__plexus_utils'],
        exports = [':main_deps___org_codehaus_plexus__plexus_utils'],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-error-diagnostics:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_error_diagnostics',
        actual = ':main_deps___org_apache_maven__maven_error_diagnostics__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-error-diagnostics:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_error_diagnostics__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_error_diagnostics__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-error-diagnostics:2.2.1'],
        licenses = ['notice'],
        deps = [':main_deps___org_codehaus_plexus__plexus_container_default'],
        exports = [':main_deps___org_codehaus_plexus__plexus_container_default'],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-model:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_model',
        actual = ':main_deps___org_apache_maven__maven_model__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-model:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_model__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_model__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-model:2.2.1'],
        licenses = ['notice'],
        deps = [':main_deps___org_codehaus_plexus__plexus_utils'],
        exports = [':main_deps___org_codehaus_plexus__plexus_utils'],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-plugin-registry:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_plugin_registry',
        actual = ':main_deps___org_apache_maven__maven_plugin_registry__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-plugin-registry:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_plugin_registry__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_plugin_registry__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-plugin-registry:2.2.1'],
        licenses = ['notice'],
        deps = [
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-profile:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_profile',
        actual = ':main_deps___org_apache_maven__maven_profile__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-profile:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_profile__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_profile__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-profile:2.2.1'],
        licenses = ['notice'],
        deps = [
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-project:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_project',
        actual = ':main_deps___org_apache_maven__maven_project__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-project:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_project__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_project__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-project:2.2.1'],
        licenses = ['notice'],
        deps = [
            ':main_deps___org_apache_maven__maven_artifact',
            ':main_deps___org_apache_maven__maven_artifact_manager',
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_apache_maven__maven_plugin_registry',
            ':main_deps___org_apache_maven__maven_profile',
            ':main_deps___org_apache_maven__maven_settings',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___org_apache_maven__maven_artifact',
            ':main_deps___org_apache_maven__maven_artifact_manager',
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_apache_maven__maven_plugin_registry',
            ':main_deps___org_apache_maven__maven_profile',
            ':main_deps___org_apache_maven__maven_settings',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-repository-metadata:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_repository_metadata',
        actual = ':main_deps___org_apache_maven__maven_repository_metadata__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-repository-metadata:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_repository_metadata__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_repository_metadata__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-repository-metadata:2.2.1'],
        licenses = ['notice'],
        deps = [':main_deps___org_codehaus_plexus__plexus_utils'],
        exports = [':main_deps___org_codehaus_plexus__plexus_utils'],
        runtime_deps = [],
    )

    # from org.apache.maven:maven-settings:2.2.1
    native.alias(name = 'main_deps___org_apache_maven__maven_settings',
        actual = ':main_deps___org_apache_maven__maven_settings__2_2_1',
        visibility = ['//visibility:public'],
    )

    # from org.apache.maven:maven-settings:2.2.1
    native.java_import(name = 'main_deps___org_apache_maven__maven_settings__2_2_1',
        jars = ['@main_deps___org_apache_maven__maven_settings__2_2_1//file'],
        tags = ['maven_coordinates=org.apache.maven:maven-settings:2.2.1'],
        licenses = ['notice'],
        deps = [
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___org_apache_maven__maven_model',
            ':main_deps___org_codehaus_plexus__plexus_container_default',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.bouncycastle:bcprov-jdk15on:1.52
    native.alias(name = 'main_deps___org_bouncycastle__bcprov_jdk15on',
        actual = ':main_deps___org_bouncycastle__bcprov_jdk15on__1_52',
        visibility = ['//visibility:public'],
    )

    # from org.bouncycastle:bcprov-jdk15on:1.52
    native.java_import(name = 'main_deps___org_bouncycastle__bcprov_jdk15on__1_52',
        jars = ['@main_deps___org_bouncycastle__bcprov_jdk15on__1_52//file'],
        tags = ['maven_coordinates=org.bouncycastle:bcprov-jdk15on:1.52'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1
    native.alias(name = 'main_deps___org_codehaus_plexus__plexus_container_default',
        actual = ':main_deps___org_codehaus_plexus__plexus_container_default__1_0_alpha_9_stable_1',
        visibility = ['//visibility:public'],
    )

    # from org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1
    native.java_import(name = 'main_deps___org_codehaus_plexus__plexus_container_default__1_0_alpha_9_stable_1',
        jars = ['@main_deps___org_codehaus_plexus__plexus_container_default__1_0_alpha_9_stable_1//file'],
        tags = ['maven_coordinates=org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1'],
        licenses = [],
        deps = [
            ':main_deps___classworlds__classworlds',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        exports = [
            ':main_deps___classworlds__classworlds',
            ':main_deps___org_codehaus_plexus__plexus_utils',
        ],
        runtime_deps = [],
    )

    # from org.codehaus.plexus:plexus-utils:1.5.15
    native.alias(name = 'main_deps___org_codehaus_plexus__plexus_utils',
        actual = ':main_deps___org_codehaus_plexus__plexus_utils__1_5_15',
        visibility = ['//visibility:public'],
    )

    # from org.codehaus.plexus:plexus-utils:1.5.15
    native.java_import(name = 'main_deps___org_codehaus_plexus__plexus_utils__1_5_15',
        jars = ['@main_deps___org_codehaus_plexus__plexus_utils__1_5_15//file'],
        tags = ['maven_coordinates=org.codehaus.plexus:plexus-utils:1.5.15'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.hamcrest:hamcrest-core:1.3
    native.alias(name = 'main_deps___org_hamcrest__hamcrest_core',
        actual = ':main_deps___org_hamcrest__hamcrest_core__1_3',
        visibility = ['//visibility:public'],
    )

    # from org.hamcrest:hamcrest-core:1.3
    native.java_import(name = 'main_deps___org_hamcrest__hamcrest_core__1_3',
        jars = ['@main_deps___org_hamcrest__hamcrest_core__1_3//file'],
        tags = ['maven_coordinates=org.hamcrest:hamcrest-core:1.3'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.hamcrest:hamcrest-library:1.3
    native.alias(name = 'main_deps___org_hamcrest__hamcrest_library',
        actual = ':main_deps___org_hamcrest__hamcrest_library__1_3',
        visibility = ['//visibility:public'],
    )

    # from org.hamcrest:hamcrest-library:1.3
    native.java_import(name = 'main_deps___org_hamcrest__hamcrest_library__1_3',
        jars = ['@main_deps___org_hamcrest__hamcrest_library__1_3//file'],
        tags = ['maven_coordinates=org.hamcrest:hamcrest-library:1.3'],
        licenses = ['notice'],
        deps = [':main_deps___org_hamcrest__hamcrest_core'],
        exports = [':main_deps___org_hamcrest__hamcrest_core'],
        runtime_deps = [],
    )

    # from org.ow2.asm:asm-commons:5.0.1
    native.alias(name = 'main_deps___org_ow2_asm__asm_commons',
        actual = ':main_deps___org_ow2_asm__asm_commons__5_0_1',
        visibility = ['//visibility:public'],
    )

    # from org.ow2.asm:asm-commons:5.0.1
    native.java_import(name = 'main_deps___org_ow2_asm__asm_commons__5_0_1',
        jars = ['@main_deps___org_ow2_asm__asm_commons__5_0_1//file'],
        tags = ['maven_coordinates=org.ow2.asm:asm-commons:5.0.1'],
        licenses = ['notice'],
        deps = [':main_deps___org_ow2_asm__asm_tree'],
        exports = [':main_deps___org_ow2_asm__asm_tree'],
        runtime_deps = [],
    )

    # from org.ow2.asm:asm-tree:5.0.1
    native.alias(name = 'main_deps___org_ow2_asm__asm_tree',
        actual = ':main_deps___org_ow2_asm__asm_tree__5_0_1',
        visibility = ['//visibility:public'],
    )

    # from org.ow2.asm:asm-tree:5.0.1
    native.java_import(name = 'main_deps___org_ow2_asm__asm_tree__5_0_1',
        jars = ['@main_deps___org_ow2_asm__asm_tree__5_0_1//file'],
        tags = ['maven_coordinates=org.ow2.asm:asm-tree:5.0.1'],
        licenses = ['notice'],
        deps = [':main_deps___org_ow2_asm__asm'],
        exports = [':main_deps___org_ow2_asm__asm'],
        runtime_deps = [],
    )

    # from org.ow2.asm:asm:5.0.1
    native.alias(name = 'main_deps___org_ow2_asm__asm',
        actual = ':main_deps___org_ow2_asm__asm__5_0_1',
        visibility = ['//visibility:public'],
    )

    # from org.ow2.asm:asm:5.0.1
    native.java_import(name = 'main_deps___org_ow2_asm__asm__5_0_1',
        jars = ['@main_deps___org_ow2_asm__asm__5_0_1//file'],
        tags = ['maven_coordinates=org.ow2.asm:asm:5.0.1'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.robolectric:android-all:5.0.2_r3-robolectric-r0
    native.alias(name = 'main_deps___org_robolectric__android_all',
        actual = ':main_deps___org_robolectric__android_all__5_0_2_r3_robolectric_r0',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:android-all:5.0.2_r3-robolectric-r0
    native.java_import(name = 'main_deps___org_robolectric__android_all__5_0_2_r3_robolectric_r0',
        jars = ['@main_deps___org_robolectric__android_all__5_0_2_r3_robolectric_r0//file'],
        tags = ['maven_coordinates=org.robolectric:android-all:5.0.2_r3-robolectric-r0'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.robolectric:annotations:3.8
    native.alias(name = 'main_deps___org_robolectric__annotations',
        actual = ':main_deps___org_robolectric__annotations__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:annotations:3.8
    native.java_import(name = 'main_deps___org_robolectric__annotations__3_8',
        jars = ['@main_deps___org_robolectric__annotations__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:annotations:3.8'],
        licenses = ['notice'],
        deps = [':main_deps___org_robolectric__shadowapi'],
        exports = [':main_deps___org_robolectric__shadowapi'],
        runtime_deps = [],
    )

    # from org.robolectric:junit:3.8
    native.alias(name = 'main_deps___org_robolectric__junit',
        actual = ':main_deps___org_robolectric__junit__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:junit:3.8
    native.java_import(name = 'main_deps___org_robolectric__junit__3_8',
        jars = ['@main_deps___org_robolectric__junit__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:junit:3.8'],
        licenses = ['notice'],
        deps = [
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__sandbox',
            ':main_deps___org_robolectric__shadowapi',
        ],
        exports = [
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__sandbox',
            ':main_deps___org_robolectric__shadowapi',
        ],
        runtime_deps = [],
    )

    # from org.robolectric:resources:3.8
    native.alias(name = 'main_deps___org_robolectric__resources',
        actual = ':main_deps___org_robolectric__resources__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:resources:3.8
    native.java_import(name = 'main_deps___org_robolectric__resources__3_8',
        jars = ['@main_deps___org_robolectric__resources__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:resources:3.8'],
        licenses = ['notice'],
        deps = [
            ':main_deps___com_google_guava__guava',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__utils',
        ],
        exports = [
            ':main_deps___com_google_guava__guava',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__utils',
        ],
        runtime_deps = [],
    )

    # from org.robolectric:robolectric:3.8
    native.alias(name = 'main_deps___org_robolectric__robolectric',
        actual = ':main_deps___org_robolectric__robolectric__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:robolectric:3.8
    native.java_import(name = 'main_deps___org_robolectric__robolectric__3_8',
        jars = ['@main_deps___org_robolectric__robolectric__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:robolectric:3.8'],
        licenses = ['notice'],
        deps = [
            ':main_deps___com_thoughtworks_xstream__xstream',
            ':main_deps___org_apache_ant__ant',
            ':main_deps___org_apache_maven__maven_ant_tasks',
            ':main_deps___org_bouncycastle__bcprov_jdk15on',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__junit',
            ':main_deps___org_robolectric__resources',
            ':main_deps___org_robolectric__sandbox',
            ':main_deps___org_robolectric__shadows_framework',
            ':main_deps___org_robolectric__utils',
        ],
        exports = [
            ':main_deps___com_thoughtworks_xstream__xstream',
            ':main_deps___org_apache_ant__ant',
            ':main_deps___org_apache_maven__maven_ant_tasks',
            ':main_deps___org_bouncycastle__bcprov_jdk15on',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__junit',
            ':main_deps___org_robolectric__resources',
            ':main_deps___org_robolectric__sandbox',
            ':main_deps___org_robolectric__shadows_framework',
            ':main_deps___org_robolectric__utils',
        ],
        runtime_deps = [],
    )

    # from org.robolectric:sandbox:3.8
    native.alias(name = 'main_deps___org_robolectric__sandbox',
        actual = ':main_deps___org_robolectric__sandbox__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:sandbox:3.8
    native.java_import(name = 'main_deps___org_robolectric__sandbox__3_8',
        jars = ['@main_deps___org_robolectric__sandbox__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:sandbox:3.8'],
        licenses = ['notice'],
        deps = [
            ':main_deps___com_google_guava__guava',
            ':main_deps___org_ow2_asm__asm',
            ':main_deps___org_ow2_asm__asm_commons',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__shadowapi',
            ':main_deps___org_robolectric__utils',
        ],
        exports = [
            ':main_deps___com_google_guava__guava',
            ':main_deps___org_ow2_asm__asm',
            ':main_deps___org_ow2_asm__asm_commons',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__shadowapi',
            ':main_deps___org_robolectric__utils',
        ],
        runtime_deps = [],
    )

    # from org.robolectric:shadowapi:3.8
    native.alias(name = 'main_deps___org_robolectric__shadowapi',
        actual = ':main_deps___org_robolectric__shadowapi__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:shadowapi:3.8
    native.java_import(name = 'main_deps___org_robolectric__shadowapi__3_8',
        jars = ['@main_deps___org_robolectric__shadowapi__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:shadowapi:3.8'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.robolectric:shadows-framework:3.8
    native.alias(name = 'main_deps___org_robolectric__shadows_framework',
        actual = ':main_deps___org_robolectric__shadows_framework__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:shadows-framework:3.8
    native.java_import(name = 'main_deps___org_robolectric__shadows_framework__3_8',
        jars = ['@main_deps___org_robolectric__shadows_framework__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:shadows-framework:3.8'],
        licenses = ['notice'],
        deps = [
            ':main_deps___com_almworks_sqlite4java__sqlite4java',
            ':main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework',
            ':main_deps___com_ibm_icu__icu4j',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__resources',
            ':main_deps___org_robolectric__utils',
        ],
        exports = [
            ':main_deps___com_almworks_sqlite4java__sqlite4java',
            ':main_deps___com_google_android_apps_common_testing_accessibility_framework__accessibility_test_framework',
            ':main_deps___com_ibm_icu__icu4j',
            ':main_deps___org_robolectric__annotations',
            ':main_deps___org_robolectric__resources',
            ':main_deps___org_robolectric__utils',
        ],
        runtime_deps = [],
    )

    # from org.robolectric:utils:3.8
    native.alias(name = 'main_deps___org_robolectric__utils',
        actual = ':main_deps___org_robolectric__utils__3_8',
        visibility = ['//visibility:public'],
    )

    # from org.robolectric:utils:3.8
    native.java_import(name = 'main_deps___org_robolectric__utils__3_8',
        jars = ['@main_deps___org_robolectric__utils__3_8//file'],
        tags = ['maven_coordinates=org.robolectric:utils:3.8'],
        licenses = ['notice'],
        deps = [':main_deps___org_robolectric__annotations'],
        exports = [':main_deps___org_robolectric__annotations'],
        runtime_deps = [],
    )

    # from xmlpull:xmlpull:1.1.3.1
    native.alias(name = 'main_deps___xmlpull__xmlpull',
        actual = ':main_deps___xmlpull__xmlpull__1_1_3_1',
        visibility = ['//visibility:public'],
    )

    # from xmlpull:xmlpull:1.1.3.1
    native.java_import(name = 'main_deps___xmlpull__xmlpull__1_1_3_1',
        jars = ['@main_deps___xmlpull__xmlpull__1_1_3_1//file'],
        tags = ['maven_coordinates=xmlpull:xmlpull:1.1.3.1'],
        licenses = ['unencumbered'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from xpp3:xpp3_min:1.1.4c
    native.alias(name = 'main_deps___xpp3__xpp3_min',
        actual = ':main_deps___xpp3__xpp3_min__1_1_4c',
        visibility = ['//visibility:public'],
    )

    # from xpp3:xpp3_min:1.1.4c
    native.java_import(name = 'main_deps___xpp3__xpp3_min__1_1_4c',
        jars = ['@main_deps___xpp3__xpp3_min__1_1_4c//file'],
        tags = ['maven_coordinates=xpp3:xpp3_min:1.1.4c'],
        licenses = [
            'notice',
            'unencumbered',
        ],
        deps = [],
        exports = [],
        runtime_deps = [],
    )


